# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/*, feature/*, fix/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  - name: Codecov
    uses: codecov/codecov-action@v1.0.7
    with:
      # Specify whether or not CI build should fail if Codecov runs into an error during upload
      fail_ci_if_error: true
